# Generated by Django 5.2.11 on 2026-04-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('qualifications', models.CharField(help_text='e.g., MBBS, MD - Cardiology', max_length=255)),
                ('license_number', models.CharField(help_text='Medical board license number', max_length=50, unique=True)),
                ('hospital_affiliation', models.CharField(max_length=255)),
                ('department', models.CharField(help_text='e.g., ER, Surgery, ICU', max_length=100)),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Checked by admin to allow blood requests')),
                ('profilePhoto', models.ImageField(upload_to='doctor_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Hospital or Blood Bank ID', max_length=50, unique=True)),
                ('designation', models.CharField(help_text='e.g., Lab Tech, Inventory Manager, Nurse', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('branch_location', models.CharField(default='Main Hospital Blood Bank', max_length=150)),
                ('shift', models.CharField(choices=[('Morning', 'Morning Shift'), ('Evening', 'Evening Shift'), ('Night', 'Night Shift')], default='Morning', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
