# Generated by Django 5.2.11 on 2026-04-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicalOfficers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="active",
            field=models.BooleanField(
                default=False, help_text="doctor is retired or not"
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("TEC", "Lab Technician"),
                    ("MANG", "Manager"),
                    ("NURSE", "Nurse"),
                ],
                help_text="e.g., Lab Tech, Inventory Manager, Nurse",
                max_length=100,
            ),
        ),
    ]
