# Generated by Django 5.2.10 on 2026-04-21 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodinventor', '0001_initial'),
        ('medicalOfficers', '0002_doctorprofile_active_alter_staffprofile_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('units_requested', models.PositiveIntegerField()),
                ('units_approved', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('urgency', models.CharField(default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('approval_note', models.TextField(blank=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='medicalOfficers.staffprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='medicalOfficers.doctorprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_requests', to='medicalOfficers.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('ADJUST', 'Adjust'), ('DELETE', 'Delete'), ('MARK_DAMAGED', 'Mark Damaged'), ('MARK_EXPIRED', 'Mark Expired')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING_ADMIN_REVIEW', 'Pending Admin Review'), ('PENDING_QUALITY_CHECK', 'Pending Quality Check'), ('PENDING_FINAL_ADMIN_APPROVAL', 'Pending Final Admin Approval'), ('APPROVED_READY_TO_EXECUTE', 'Approved Ready To Execute'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_ADMIN_REVIEW', max_length=40)),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('quantity_delta', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('collected_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('quality_note', models.TextField(blank=True)),
                ('final_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_change_admin_reviewed', to=settings.AUTH_USER_MODEL)),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_change_requests', to='bloodinventor.bloodbank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_change_created', to=settings.AUTH_USER_MODEL)),
                ('final_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_change_final_approved', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='bloodinventor.bloodinventory')),
                ('quality_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_change_quality_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
