# Generated by Django 5.2.11 on 2026-03-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
